{
    "name": "Vesna Macarons Courier",
    "version": "19.0.1.0.0",
    "summary": "Courier zones, routes and GPX-based delivery tracking",
    "category": "Inventory/Delivery",
    "author": "H O R R O N",
    "website": "https://example.com",
    "license": "LGPL-3",
    "depends": ["base", "mail", "stock", "web", "website"],
    "data": [
        "security/courier_security.xml",
        "security/ir.model.access.csv",
        "security/courier_rules.xml",
        "data/courier_sequence.xml",
        "data/courier_data.xml",
        "views/courier_zone_views.xml",
        "views/courier_gpx_track_views.xml",
        "views/courier_dispatch_batch_views.xml",
        "views/courier_route_views.xml",
        "views/courier_route_stop_views.xml",
        "views/courier_driver_shift_views.xml",
        "views/res_partner_views.xml",
        "views/stock_picking_views.xml",
        "wizard/courier_route_generate_wizard_views.xml",
        "views/courier_menu.xml",
        "views/courier_website_templates.xml",
        "report/courier_route_report.xml"
    ],
    "demo": [
        "demo/courier_demo.xml"
    ],
    "post_init_hook": "post_init_hook",
    "application": True,
    "installable": True,
    "web_icon": "vesna_macarons_courier,static/description/icon.png",
}
