{
    "name": "HR Hospital",
    "version": "19.0.6.0.0",
    "summary": "Hospital workflow: patients, doctors, visits, diagnoses, and schedules.",
    "category": "Healthcare",
    "author": "H0RR0N",
    "website": "https://github.com/H0RR0N",
    "license": "LGPL-3",
    "depends": ["base"],
    "data": [
        "security/hr_hospital_security.xml",
        "security/ir.model.access.csv",
        "wizards/hr_hospital_mass_reassign_doctor_wizard_views.xml",
        "wizards/hr_hospital_disease_report_wizard_views.xml",
        "wizards/hr_hospital_reschedule_visit_wizard_views.xml",
        "wizards/hr_hospital_doctor_schedule_wizard_views.xml",
        "wizards/hr_hospital_patient_card_export_wizard_views.xml",
        "reports/hr_hospital_doctor_report_templates.xml",
        "views/hr_hospital_patient_views.xml",
        "views/hr_hospital_doctor_views.xml",
        "views/hr_hospital_visit_views.xml",
        "views/hr_hospital_disease_views.xml",
        "views/hr_hospital_contact_person_views.xml",
        "views/hr_hospital_doctor_speciality_views.xml",
        "views/hr_hospital_doctor_schedule_views.xml",
        "views/hr_hospital_patient_doctor_history_views.xml",
        "views/hr_hospital_medical_diagnosis_views.xml",
        "views/hr_hospital_menus.xml",
        "data/hr_hospital_disease_data.xml",
    ],
    "demo": [
        "demo/hr_hospital_speciality_demo.xml",
        "demo/hr_hospital_doctor_users_demo.xml",
        "demo/hr_hospital_doctor_demo.xml",
        "demo/hr_hospital_contact_person_demo.xml",
        "demo/hr_hospital_patient_demo.xml",
        "demo/hr_hospital_disease_demo.xml",
        "demo/hr_hospital_visit_demo.xml",
        "demo/hr_hospital_diagnosis_demo.xml",
        "demo/hr_hospital_schedule_demo.xml",
        "demo/hr_hospital_doctor_history_demo.xml",
    ],
    "installable": True,
    "application": True,
    "image": "static/description/icon.png",
    "images": ["static/description/baner.png"],
}
